LIBS-614 - Rename to springtainer-awss3mock
springboot-testcontainer/springboot-testcontainer-awss3mock pull request #10
Opened 2019-12-18 12:09 UTC by hennes-maertins

2019-12-18 12:36 UTC, mrhnrk requested changes

2019-12-18 12:36 UTC, loefflefarn commented on pom.xml
>    <version>1.0.0-RC3</version>
Release

2019-12-18 12:43 UTC, hennes-maertins commented on pom.xml
>    <version>1.0.0-RC3</version>
Fixed

2019-12-18 12:46 UTC, mrhnrk approved these changes

2019-12-19 09:23 UTC, julian-eggers approved these changes

2019-12-19 09:24 UTC, merged