LIBS-729 - Update dependencies
springboot-testcontainer/springboot-testcontainer-awss3mock pull request #11
Opened 2020-06-16 14:34 UTC by loefflefarn

2020-06-16 14:39 UTC, loefflefarn commented
Here is some issue with the update to the latest `springtainer-common` version `1.1.2`. The docker-java-client in version `3.2.1` cannot connect to the awss3mock container and throws an exception that it cannot find a property with name 'path'. With the previous used docker-java-client version `3.1.1` it works... Have you any idea? @julian-eggers

2020-06-17 12:00 UTC, julian-eggers requested changes

2020-06-17 12:00 UTC, julian-eggers commented on src/main/java/com/avides/springboot/springtainer/awss3mock/EmbeddedAwsS3MockContainerAutoConfiguration.java
> +    public static class AwsS3MockContainer extends AbstractBuildingEmbeddedContainer<AwsS3MockProperties>
Warum ist die Klasse static? Macht doch an dieser Stelle eigentlich keinen Sinn oder? Wurde in den anderen Springtainern auch nicht gemacht...

2020-06-17 12:01 UTC, loefflefarn commented on src/main/java/com/avides/springboot/springtainer/awss3mock/EmbeddedAwsS3MockContainerAutoConfiguration.java
> +    public static class AwsS3MockContainer extends AbstractBuildingEmbeddedContainer<AwsS3MockProperties>
Bei manchen habe ich das ebenfalls angepasst, da IntelliJ mir hier ein Warning angezeigt hat, dass diese Klasse `static` sein sollte.

2020-06-17 14:51 UTC, fegbers approved these changes

2020-06-17 15:03 UTC, julian-eggers approved these changes

2020-06-17 15:03 UTC, merged